### ISSUE TITLE
CVE

### ISSUE THREAD

**Issue by C1ph3R-s** [okeuday/pest#2]
Hi,

First of all the project is very cool, and It has gave me a big help in my personal project.
Just a question about findings, could you give me CVE number for each vulnerabilities what it capable to find?

**Comment by okeuday** [comment]
@C1ph3R-s Glad it has helped you.  The analysis pest does is for finding attack vectors related to Erlang/OTP itself.  These are potential security problems in a [relatively short list](https://github.com/okeuday/pest/blob/f1b644ec4fbbdda1645994e58c4f4ab042189a22/src/pest.erl#L153-L215).  The list is something that can be improved if functions are added or removed from Erlang/OTP.  However, these are potential security problems with different levels of severity.  There are no CVE numbers attached to these potential security problems because the goal is to catch problems before CVE numbers are created.

For example, a NIF could have a problem but pest will only see the function that loads the NIF.  That means external linked in C is not scanned by pest and is only seen as a potential problem (if Erlang source code was used instead, it would be safer as the Erlang source code changes instead of C source code).

**Comment by okeuday** [comment]
@C1ph3R-s If you needed OpenSSL CVEs based on the version you are using, use `./pest.erl -V crypto`
